# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 916982208333ae17e1f601ad00a182def6a5729d9a8fba8a10b375e655ca2e0d24fabfbc159ca76727df983b540605355c356a1e1f44a6a318586cf262117ba9

test:
  secret_key_base: b3defd1fe59e013297d37766b0910d0546e874cf68c5a3f507eaadabe8919707444fe22bd435bd21077f63044b1441319b67e164affc6b915c5af7c5df4a0235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
